add(letters): Add letters argument as per Dustin Kirklands implementation
anthonkendel/javascript-petname pull request #31
Opened 2022-03-17 04:58 UTC by robbash

Hey @anthonkendel. Found your JS implementation today and much appreciate the work.

One thing I was missing so far is the `--letters` argument (limitation of the word length) hence why I created this change.

2022-03-17 18:19 UTC, anthonkendel requested changes
Mostly looks fine, some minor comments.

2022-03-17 18:19 UTC, anthonkendel commented on src/petname.js
> +    adjectives = adjectives.filter(filterFunc);
inline the filters, and remove the filterByLength function to keep it simpler.

```
adjectives.filter(v => v.length <= letters);
adverbs.filter(v => v.length <= letters);
names.filter(v => v.length <= letters);
```

2022-03-17 18:19 UTC, anthonkendel commented on src/petname.js
> +function generatePetname({ words = 2, separator = '-', letters = 0 } = {}) {
use `undefined` as default value for `letters`

2022-03-18 00:26 UTC, robbash commented
Thanks. Code updated...

2022-03-19 12:13 UTC, anthonkendel approved these changes

2022-03-19 12:16 UTC, merged